export const LOGIN = 'LOGIN';
export const API_REQUEST_SUCCESS = 'API_REQUEST';

export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const ALEATORY_QUESTS = 'ALEATORY_QUESTS';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const QUESTION_DONE = 'QUESTION_DONE';
export const TOKEN = 'TOKEN';
export const QUESTION_POINTS = 'QUESTION';
export const QUESTION_TIME = 'QUESTION_TIME';
